@startuml
' Класс Пицца
class Пицца {
    - название: str
    - тесто: str
    - соус: str
    - начинка: list
    - цена: float
    + __str__(): str
    + подготовить()
    + испечь()
    + нарезать()
    + упаковать()
}

' Классы-наследники Пицца
class ПиццаПепперони {
    + __init__()
}

class ПиццаБарбекю {
    + __init__()
}

class ПиццаДарыМоря {
    + __init__()
}

' Наследование
Пицца <|-- ПиццаПепперони
Пицца <|-- ПиццаБарбекю
Пицца <|-- ПиццаДарыМоря

' Класс Заказ
class Заказ {
    - заказанные_пиццы: list
    - счетчик_заказов: int
    + __init__()
    + __str__(): str
    + добавить(пицца)
    + сумма(): float
    + выполнить()
}

' Класс Терминал
class Терминал {
    - меню: list
    - заказ: Заказ
    - отображать_меню: bool
    + __init__()
    + __str__(): str
    + показать_меню()
    + обработать_команду(пункт_меню)
    + рассчитать_сдачу(оплата): float
    + принять_оплату()
}

' Взаимосвязи
Терминал "1" --> "1" Заказ : управляет
Заказ "1" --> "M" Пицца : содержит

@enduml