@startuml
abstract class ПишущаяПринадлежность {
    +цвет: str
    -_толщина_линии: float
    +{abstract} писать()
    -__очистить()
}

class Карандаш {
    +твердость_грифеля: str
    -_заточен: bool
    +писать()
    -__точить()
}

class Ручка {
    +тип_ручки: str
    -_чернила: int
    +писать()
    -__проверить_чернила()
}

class ГелеваяРучка {
    +материал_корпуса: str
    -__прозрачность: bool
    +писать()
    -__проверить_прозрачность()
}

ПишущаяПринадлежность <|-- Карандаш
ПишущаяПринадлежность <|-- Ручка
Ручка <|-- ГелеваяРучка
@enduml