@startuml
' Определение абстрактного класса
abstract class ПишущаяПринадлежность {
    - цвет: str
    - толщина_линии: float
    + писать(): void
}

' Класс Карандаш наследует от ПишущаяПринадлежность
class Карандаш {
    - твердость_грифеля: str
    + писать(): void
}

' Класс Ручка наследует от ПишущаяПринадлежность
class Ручка {
    - тип_ручки: str
    + писать(): void
}

' Класс ГелеваяРучка наследует от Ручка
class ГелеваяРучка {
    - материал_корпуса: str
    + писать(): void
}

' Наследование
ПишущаяПринадлежность <|-- Карандаш
ПишущаяПринадлежность <|-- Ручка
Ручка <|-- ГелеваяРучка

@enduml